image: node:8.15.0

stages:
  - build-and-deploy

job build:
  stage: build-and-deploy
  only:
    refs:
      - master
      - stage
  script:
    # INSTALL DEPENDECIES
    - npm ci --production
    # BUILD THE ASSETS
    - npm run g:build
    # CHOOSE APP_DOMAIN
    - APP_NAME=$(node -p -e "require('./package.json').name")
    - APP_DOMAIN=$(if [ "$CI_COMMIT_REF_NAME" = "stage" ]; then echo $CI_COMMIT_REF_NAME.$APP_NAME; else echo $APP_NAME; fi)
    # DEPLOY AND READ THE DEPLOYMENT ID
    - DEPLOYMENT=$(npx now deploy -t ${CI_TOKEN} | grep https | sed -r s'/^.*https:\/\/(\S+).*$/\1/g')
    - APP_DOMAIN=$(node -p -e "require('./package.json').name")
    - npx now alias set ${DEPLOYMENT} ${APP_DOMAIN} -t ${CI_TOKEN}
    - npx now rm ${APP_DOMAIN} -t ${CI_TOKEN} --safe --yes
