image: node:8.15.0

stages:
  - build-and-deploy

job everything:
  stage: build-and-deploy
  only:
    refs:
      - master
  script:
    # INSTALL DEPENDECIES
    - npm ci --production
    # BUILD THE ASSETS
    - npm run g:build
    # DEPLOY AND READ THE DEPLOYMENT ID
    - DEPLOYMENT=$(npx now deploy -t ${CI_TOKEN} | grep https | sed -r s'/^.*https:\/\/(\S+).*$/\1/g')
    - APP_DOMAIN=$(node -p -e "require('./package.json').name")
    - npx now alias set ${DEPLOYMENT} ${APP_DOMAIN} -t ${CI_TOKEN}
    - npx now rm ${APP_DOMAIN} -t ${CI_TOKEN} --safe --yes

