image: node:8.15.0

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_SHA}
  paths:
    - node_modules/

stages:
  - build-and-deploy

job setup:
  stage: build-and-deploy
  only:
    refs:
      - master
  script:
    - npm ci --production

job build:
  stage: build-and-deploy
  only:
    refs:
      - master
  script:
    - npm run g:build

job deploy:
  stage: build-and-deploy
  only:
    refs:
      - master
  script:
    - DEPLOYMENT=$(npx now deploy -t ${CI_TOKEN} | grep https | sed -r s'/^.*https:\/\/(\S+).*$/\1/g')
    - npx now alias set ${DEPLOYMENT} ${APP_DOMAIN}

job clean-up:
  stage: build-and-deploy
  only:
    refs:
      - master
  script:
    - npx now rm ${APP_DOMAIN} -t ${CI_TOKEN} --safe --yes

