name: CI

on:
  push:
    branches: 
      - master
      - stage

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    - name: install dependecies
      run: npm ci --production

    - name: build the assets
      run: npm run g:build

    - name: choose domain for deployment
    - run: | 
        APP_NAME=$(node -p -e "require('./package.json').name")
        APP_DOMAIN=$(if [ "$CI_COMMIT_REF_NAME" = "stage" ]; then echo $CI_COMMIT_REF_NAME.$APP_NAME; else echo $APP_NAME; fi)

    - name: deploy and read the deployment ID
      run: | 
        DEPLOYMENT=$(npx now deploy -t $CI_TOKEN | grep https | sed -r s'/^.*https:\/\/(\S+).*$/\1/g')
        npx now alias set $DEPLOYMENT $APP_DOMAIN -t $CI_TOKEN
        npx now rm $APP_NAME -t $CI_TOKEN --safe --yes

