name: publish

on:
  push:
    branches:
      - master
      - stage

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          version: '12.x'

      - name: Cache downloaded node dependecies
        uses: actions/cache@v1
        with:
          path: ~/.yarn # this folder set for yarn cache manually
          key: ${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn install --production --cache-folder ~/.yarn

      - name: build the assets
        run: |
          yarn g:build

      - name: deploy
        shell: bash
        env:
          PUBLISHING_TOKEN: ${{ secrets.PUBLISHING_TOKEN }}
          BRANCH: ${{ github.ref }}
        run: |
          APP_NAME=$(node -p -e "require('./package.json').name")
          APP_DOMAIN=$(if [ "$BRANCH" = "refs/heads/stage" ]; then echo stage.$APP_NAME; else echo $APP_NAME; fi)
          DEPLOYMENT=$(yarn now deploy -t $PUBLISHING_TOKEN | grep https | sed -r s'/^.*https:\/\/(\S+\.now\.sh).*$/\1/g')
          yarn now alias set $DEPLOYMENT $APP_DOMAIN -t $PUBLISHING_TOKEN
          yarn now rm $APP_NAME -t $PUBLISHING_TOKEN --safe --yes || exit 0
